"""Add budgets table

Revision ID: 46fadc0f7e55
Revises: f5f4870a54e3
Create Date: 2026-03-10 16:36:51.104254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fadc0f7e55'
down_revision: Union[str, None] = 'f5f4870a54e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Budget amount for the period'),
    sa.Column('period', sa.String(length=20), nullable=False, comment="Budget period: 'monthly' for MVP"),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Date when this budget becomes active'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active budgets are used for current tracking'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budgets_category', 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index('ix_budgets_start_date', 'budgets', ['start_date'], unique=False)
    op.create_index('ix_budgets_user_active', 'budgets', ['user_id', 'is_active'], unique=False)
    op.create_index('uq_budget_user_category_active', 'budgets', ['user_id', 'category_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_budget_user_category_active', table_name='budgets', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_budgets_user_active', table_name='budgets')
    op.drop_index('ix_budgets_start_date', table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_index('ix_budgets_category', table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
