"""Add type to transfers

Revision ID: 873c940ec7f7
Revises: d9555bc5b21b
Create Date: 2025-11-22 22:39:41.703080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873c940ec7f7'
down_revision: Union[str, None] = 'd9555bc5b21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('type', sa.String(length=20), nullable=False, server_default='generic'))

    op.create_index('ix_transfers_user_type', 'transfers', ['user_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfers_user_type', table_name='transfers')
    op.drop_column('transfers', 'type')
    # ### end Alembic commands ###
