"""Add vacation module tables with separate accrual rates

Revision ID: f5f4870a54e3
Revises: c247a298d616
Create Date: 2026-03-09 22:44:49.184767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f4870a54e3'
down_revision: Union[str, None] = 'c247a298d616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('italian_holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('is_national', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_italian_holidays_date'), 'italian_holidays', ['date'], unique=True)
    op.create_index(op.f('ix_italian_holidays_id'), 'italian_holidays', ['id'], unique=False)
    op.create_index('ix_italian_holidays_year', 'italian_holidays', ['date'], unique=False)
    op.create_table('user_holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', 'month', 'year', name='uq_user_holiday')
    )
    op.create_index(op.f('ix_user_holidays_id'), 'user_holidays', ['id'], unique=False)
    op.create_index(op.f('ix_user_holidays_user_id'), 'user_holidays', ['user_id'], unique=False)
    op.create_index('ix_user_holidays_user_month', 'user_holidays', ['user_id', 'month'], unique=False)
    op.create_table('vacation_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.Enum('FERIE', 'PERMESSO', 'ROL', name='vacation_entry_type'), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_vacation_entry_user_date')
    )
    op.create_index(op.f('ix_vacation_entries_date'), 'vacation_entries', ['date'], unique=False)
    op.create_index(op.f('ix_vacation_entries_id'), 'vacation_entries', ['id'], unique=False)
    op.create_index('ix_vacation_entries_user_date', 'vacation_entries', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_vacation_entries_user_id'), 'vacation_entries', ['user_id'], unique=False)
    op.create_index('ix_vacation_entries_user_type', 'vacation_entries', ['user_id', 'entry_type'], unique=False)
    op.create_table('vacation_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('work_hours_per_day', sa.Float(), nullable=False),
    sa.Column('ferie_days_per_month', sa.Float(), nullable=False),
    sa.Column('rol_hours_per_month', sa.Float(), nullable=False),
    sa.Column('permessi_hours_per_month', sa.Float(), nullable=False),
    sa.Column('tracking_start_date', sa.Date(), nullable=False),
    sa.Column('initial_balance_month', sa.Integer(), nullable=True),
    sa.Column('initial_balance_year', sa.Integer(), nullable=True),
    sa.Column('initial_ferie_days', sa.Float(), nullable=True),
    sa.Column('initial_rol_hours', sa.Float(), nullable=True),
    sa.Column('initial_permessi_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_vacation_settings_user')
    )
    op.create_index(op.f('ix_vacation_settings_id'), 'vacation_settings', ['id'], unique=False)
    op.create_index(op.f('ix_vacation_settings_user_id'), 'vacation_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacation_settings_user_id'), table_name='vacation_settings')
    op.drop_index(op.f('ix_vacation_settings_id'), table_name='vacation_settings')
    op.drop_table('vacation_settings')
    op.drop_index('ix_vacation_entries_user_type', table_name='vacation_entries')
    op.drop_index(op.f('ix_vacation_entries_user_id'), table_name='vacation_entries')
    op.drop_index('ix_vacation_entries_user_date', table_name='vacation_entries')
    op.drop_index(op.f('ix_vacation_entries_id'), table_name='vacation_entries')
    op.drop_index(op.f('ix_vacation_entries_date'), table_name='vacation_entries')
    op.drop_table('vacation_entries')
    op.drop_index('ix_user_holidays_user_month', table_name='user_holidays')
    op.drop_index(op.f('ix_user_holidays_user_id'), table_name='user_holidays')
    op.drop_index(op.f('ix_user_holidays_id'), table_name='user_holidays')
    op.drop_table('user_holidays')
    op.drop_index('ix_italian_holidays_year', table_name='italian_holidays')
    op.drop_index(op.f('ix_italian_holidays_id'), table_name='italian_holidays')
    op.drop_index(op.f('ix_italian_holidays_date'), table_name='italian_holidays')
    op.drop_table('italian_holidays')
    # ### end Alembic commands ###
